group: travis_latest
language: python
cache: pip
python:
    - 2.7
    - 3.6
before_install:
    - sudo apt install build-essential
    - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    - tar -xzf ta-lib-0.4.0-src.tar.gz
    - cd ta-lib/
    - ./configure --prefix=/usr
    - make
    - sudo make install
    - cd ..
install:
    - pip install -r requirements.txt
    - pip install flake8  # pytest  # add another testing frameworks later
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --ignore=E265,W2 --max-complexity=10 --max-line-length=127 --statistics
script:
    - true  # pytest --capture=sys  # add other tests here
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
